apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: go-app-argo-config
  namespace: argocd
spec:
  project: ipappk8s
  source:
    repoURL: https://github.com/rahulmathod59/argocd.git
    targetRevision: main
    path: kubeconfig
  destination:
    server: https://13.126.218.233:6443
    namespace: default
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true

